Add formula for 2.4.6
eddies/homebrew-spark-tap pull request #2
Opened 2020-10-27 12:29 UTC by dan-blanchard

2020-12-08 05:06 UTC, eddies requested changes
@dan-blanchard Sorry for not getting to this sooner! If you're up for making the change to `depends_on` and squashing down to a single commit, that would be great!

2020-12-08 05:06 UTC, eddies commented on Formula/apache-spark@2.4.6.rb
> +  depends_on :java => "1.8"
Should now be `depends_on "openjdk@8"` (see https://github.com/eddies/homebrew-spark-tap/pull/3)

2020-12-08 18:07 UTC, dan-blanchard commented
All squashed and good to go

2020-12-09 08:31 UTC, eddies approved these changes

2020-12-09 08:31 UTC, merged

2020-12-09 08:33 UTC, eddies commented
> All squashed and good to go

Thanks!